version: '3'

services:
  frontend:
    build:
      context: ./bg-next-app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./bg-flask-app/app
    ports:
      - "5000:5000"
    depends_on:
      - frontend
